### PR TITLE
GitHub Action

### LINKED ISSUE #2: Refactor GitHub Actions config
With the release of scheduled GitHub Action runs, we can also do the same thing as CircleCI.

Resource: https://developer.github.com/actions/changes/2019-04-05-scheduling-workflows/

### PR DESCRIPTION
**Pull request by JasonEtco**
This PR refactors the thing to use GitHub Actions and the new `schedule` trigger 🎉 

Closes #2

### CODE REVIEW

**Comment by JasonEtco** [comment]
I _think_ this'll work, but the `schedule` trigger only works when its on the default branch so its hard to be sure. 🚢 🎉

**Comment by johnletey** [comment]
> but the schedule trigger only works when its on the default branch

@JasonEtco Fingers crossed 🤞

**Comment by johnletey** [comment]
@JasonEtch Do you want to make the update 5 minutes like before (it’s currently 15)?

**Comment by JasonEtco** [comment]
No, I think 15 minutes is better. 5 minutes is more often than it really needs to be.

**Comment by johnletey** [comment]
Sounds good

**Pull request merged**
