### PR TITLE
Added PR Reviews 

### PR DESCRIPTION
**Pull request by HPaulson**
- Added the `PullRequestReviewCommentEvent` for activity box to filter & add to gist. PR Reviews are contributions, and should probably be included here.

- [ ] Tested
- [x] Ran prettier for code formatting
- [x] Squashed Commits

### CODE REVIEW

**Comment by JasonEtco** [comment]
Hey @Mohammed-Shoaib 👋 

> PR Reviews are contributions, and should probably be included here.

I totally agree, thanks for doing this. A couple of notes on the changes:

* this PR is really large because of the formatting changes. Please remove those changes - I made decisions around the formatting of this project, and would like to maintain those. 
* Can you also add a test for this new event? Happy to talk through that if it's helpful.
* I haven't actually been able to get this to work by manually querying `GET /users/:username/events/public`. Can you link to the relevant docs that show `PullRequestReviewCommentEvent`, and steps to create that event? I approved a PR with a comment and no event was created.

**Comment by HPaulson** [comment]
@JasonEtco This PR has become orphaned and I can no longer commit changes, however I can recreate the PR with these changes if needed. The event can be found on the [Docs](https://developer.github.com/v3/activity/event_types/#pullrequestreviewcommentevent).

Also, not quite sure what you'd need for testing the event. If you could explain that, I'll be happy to unformat, add the test, and open a new PR.

**Comment by JasonEtco** [comment]
Thanks @HPaulson!

Here's an example test: 

https://github.com/JasonEtco/activity-box/blob/24bbb8ddcc6f8a79addf11d11c7254221843f19a/tests/index.test.js#L71-L75

We'd want one similar, but with a different array of events:

```js
  it('updates the Gist with a PullRequestReviewComment event', async () => {
    nock.cleanAll() // Remove the existing mocked response
    const events = [{ type: 'PullRequestReviewComment, /* other data */ }]
    nock('https://api.github.com')
      // Get the user's recent activity
      .get('/users/clippy/events/public?per_page=100')
      .reply(200, events)
    await action(tools)
    expect(GistBox.prototype.update).toHaveBeenCalled()
    expect(GistBox.prototype.update.mock.calls[0][0]).toMatchSnapshot()
  })
```

One question about the `PullRequestReviewComment` event, if you could try this out I'd appreciate it - are multiple events generated if I leave multiple review comments in the same review? Because if so, I can see that causing problems - I often leave more than 5 review comments during a review, and I wouldn't want that to take over the whole Gist. It doesn't seem like there's an event specifically for created reviews though.

**Comment by HPaulson** [comment]
@JasonEtco Actually, this is a great point.

I'm pretty sure, as you mentioned, this would return every comment. This would get very, very annoying and fill up the gist.
The initial idea here was to have the gist simply display just one of the three options for review (see image), such as "Approved #100 in HPaulson/Repo" or "Requested Changes in #9183 in HPaulson/Repo" or something similar.

I'm quite unsure how to go about only getting the actual review data (One of the three options selected in review) since I'm not seeming to find it here on the docs. Going to continue looking into how this would be completed, please let me know if you have any further ideas.
image

**Comment by JasonEtco** [comment]
> The initial idea here was to have the gist simply display just one of the three options for review (see image), such as "Approved #100 in HPaulson/Repo" or "Requested Changes in #9183 in HPaulson/Repo" or something similar.

Yeah totally, this'd be a great addition but it doesn't look like the API lists those events 😬 I'll do some digging internally and see if it's intentional, and/or if we can just expose those events - but I wouldn't expect that to change very quickly.

**Comment by HPaulson** [comment]
I have found this payload being returned from `GET /repos/{owner}/{repo}/pulls/{pull_number}/reviews` ([Source](https://docs.github.com/en/rest/reference/pulls#list-reviews-for-a-pull-request))
```json
    "body": "Here is the body for the review.",
    "state": "APPROVED",
    "html_url": "https://github.com/octocat/Hello-World/pull/12#pullrequestreview-80",
    "pull_request_url": "https://api.github.com/repos/octocat/Hello-World/pulls/12",
```

Which has `state` that  shows `APPROVED`, and I'm assuming the other two possible states as well, however unsure how this could correlate to the event payload.

**Comment by JasonEtco** [comment]
That API would be great, but it assumes we have an `owner/repo` to look at, which we don't - we want to base everything off of the user. We could do something naive like look for reviews that the user has created in all of the repos found in their public events - but I don't think that'll be accurate or useful. Unfortunately, I don't think we can implement this given the current API limitation 😞 I appreciate the PR and the discussion though!

**Comment by HPaulson** [comment]
This for sure seems to be the case. Hopefully it'll be able to be added in the future! 

Thanks for your time!

**Pull request closed without merging**
