### PR TITLE
Edit documentation

### PR DESCRIPTION
**Pull request by Mohammed-Shoaib**
Hey,

:confetti_ball::tada: Thank you for making this project! :tada::confetti_ball:

I was confused about making activity box work as the instructions do not describe about creating a secret. :key:

I made the following changes: :mag:
1. Rename file `activity-box.yml` to `activity.yml` as this seems to work.
2. Give the user instructions on creating a secret for the environment variable `GH_PAT`.

Let me know for any further changes, I'd love to contribute! :unicorn:

Best,
Mohammed Shoaib

### CODE REVIEW

**Comment by JasonEtco** [comment]
Hey @Mohammed-Shoaib! Thanks for opening this 🙏 There are a lot of changes in this PR, it'd be easier to work with if those changes were separated.

I think that the point about documenting how to create the secret is really helpful, I'd like to add that to the **Project setup** list.

Renaming the file isn't necessary, but what I think you're encountering is a requirement that after forking a repo with an action in it, you need to push a change to the workflow file for Actions to notice it. That's not true for a "template repository" - so we can add that to the docs as well.

**Comment by Mohammed-Shoaib** [comment]
Thank you for reviewing my pull request! :blush: Yes, I agree there are many changes in this PR, I'll separate them out so that they are easier to work with, sorry about not doing this earlier.

Apologies but I am a bit confused about making it work without renaming the file :construction_worker:. I think it'd be nice if we could add documentation on explaining "push a change to the workflow file for Actions to notice it".

Would you prefer if I removed all the changes and only kept the change of adding the secret in the **Project setup** list? :key:

**Comment by JasonEtco** [comment]
> Would you prefer if I removed all the changes and only kept the change of adding the secret in the Project setup list? 🔑

Let's start here with a separate PR for that 👍 

> I think it'd be nice if we could add documentation on explaining "push a change to the workflow file for Actions to notice it".

I'd instead opt to include docs on creating a repo from the template repo, which doesn't require a change to the workflow for it to work. Chunking it out into a separate PR will help clarify that! I don't want to steal your thunder, but I can open that change and ping you on it if you'd like.

**Comment by Mohammed-Shoaib** [comment]
Sure, that sounds great! I'll create a new PR for creating a **secret**.

Thank you so much for explaining me on using the template repo, I understand it now! I'll create a separate PR for that too.

I'll close this PR and get back to you as soon as I can :relaxed:

**Comment by JasonEtco** [comment]
No rush! I appreciate your time, willingness to accept feedback, and contributions ✨ ❤️

**Pull request closed without merging**
